#prettier-ignore
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-test-test
  namespace: default

spec:
  replicas: 1
  selector:
    matchLabels:
      app: argo-test-test
  template:
    metadata:
      labels:
        app: argo-test-test
    spec:
      containers:
        - name: my-node-app
          image: node:18
          command: ["node", "-e", "console.log('Hello from Kubernetes!'); setInterval(() => {}, 1000);"]

# ---
apiVersion: v1
kind: Service
metadata:
  name: argo-test-test-service
  namespace: default
spec:
  selector:
    app: argo-test-test
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP
