#prettier-ignore
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-test-test
  namespace: default

spec:
  replicas: 1
  selector:
    matchLabels:
      app: argo-test-test
  template:
    metadata:
      labels:
        app: argo-test-test
    spec:
      containers:
        - name: argo-test-test
          image: docker.io/otcdigital/argo-test-test:1.0.0
          ports:
            - containerPort: 3000
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: nodejs-hello-service
#   namespace: default
# spec:
#   selector:
#     app: nodejs-hello
#   ports:
#     - port: 80
#       targetPort: 3000
#   type: ClusterIP
